// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelsDB;

#nullable disable

namespace SPA_NetCore_Foundation2_01.Migrations.Sqlite
{
    [DbContext(typeof(ModelsDbContext_Sqlite))]
    [Migration("20221011072501_InitialCreate")]
    partial class InitialCreate
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("ModelsDB.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idUser");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            idUser = 1,
                            PasswordHash = "1111",
                            SignName = "test01"
                        },
                        new
                        {
                            idUser = 2,
                            PasswordHash = "1111",
                            SignName = "test02"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
